name: Deploy Staging
on:
  push:
    branches:
      - staging
jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Command
        uses: D3rHase/ssh-command-action@v0.2
        with:
          HOST: ${{ secrets.ADDRESS_VPS_02 }}
          USER: ${{ secrets.USER_VPS_02 }}
          PRIVATE_SSH_KEY: ${{ secrets.PRIVATE_SSH_KEY_VPS_02 }}
          COMMAND: 'data/www/web/staging/movies/below/deploy/staging.sh'



